### ISSUE TITLE
chat_item.timstamp is not correct as expected

### ISSUE THREAD

**Issue by WENPIN1** [lemolatoon/youtube_chat_rs#9]
Dear owner,

If we change the test case to show the chat_item.timestamp, it will be incorrect because the timestamp seems to be converted from micro-second precision to milli-second precision.

https://github.com/lemolatoon/youtube_chat_rs/blob/4476c3b7ee64c9a8a0ddc9bcd066e7ffd3925cbf/youtube_chat_example/src/main.rs#L11

test case:
.on_chat(|chat_item| println!("{:?} {:?}", chat_item.timestamp, chat_item.message))

https://github.com/lemolatoon/youtube_chat_rs/blob/4476c3b7ee64c9a8a0ddc9bcd066e7ffd3925cbf/youtube_chat/src/parser.rs#L276

<img width="1122" alt="截圖 2024-12-16 17 56 04" src="https://github.com/user-attachments/assets/a5df0643-e6d9-4bfd-b919-11dc9a275e4e" />

Regards,
-Patrick, Yeh

**Comment by WENPIN1** [comment]
Forget to thank for all your efforts!

Thank you millions!
-Patrick, Yeh

**Comment by lemolatoon** [comment]
Hi @WENPIN1 !
Thank you for posting this issue! It seems you are right: this would be fixed by editing this line easily.
https://github.com/lemolatoon/youtube_chat_rs/blob/4476c3b7ee64c9a8a0ddc9bcd066e7ffd3925cbf/youtube_chat/src/parser.rs#L276
I'll fix this and make a release.

**Comment by lemolatoon** [comment]
@WENPIN1 
This fix at #10 is released as v0.2.2.

**Comment by WENPIN1** [comment]
@lemolatoon 

Thank you very much!
I just verify it has been fixed on the new release.
I may shine this crate over the python module "pychat" .
